[package]
name = "circle_factory"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = { version = "21.7.7" }
circle       = { path = "../circle" }

[dev-dependencies]
soroban-sdk = { version = "21.7.7", features = ["testutils"] }
circle       = { path = "../circle", features = ["testutils"] }

[features]
testutils = ["soroban-sdk/testutils"]
