# Funding links shown on the GitHub Sponsor button
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors
github: [CIRCLEUP-AJO]

# Custom sponsorship links
custom:
  - https://stellar.org/foundation
